# Generated by Django 4.2.3 on 2024-09-16 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_alter_trainer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='backend.trainer'),
        ),
    ]
