# Generated by Django 4.2.3 on 2024-10-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_training_is_recurring_training_parent_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.gym'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.trainer'),
        ),
    ]
