# Generated by Django 4.2.3 on 2024-10-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_subscription_gym_subscription_trainer'),
    ]

    operations = [
    ]
