# Generated by Django 4.2.3 on 2024-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20241001_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
