# Generated by Django 4.2.3 on 2024-10-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_customuser_sports_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='gender',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10),
        ),
    ]
