# Generated by Django 4.2.3 on 2024-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_subscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_new_client',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='makeup_lessons',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trainer',
        ),
        migrations.AddField(
            model_name='subscription',
            name='client_type',
            field=models.CharField(default='default_type', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='training_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='MakeupLesson',
        ),
    ]
