# Generated by Django 4.2.3 on 2024-10-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_customuser_is_new_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='training_days',
        ),
        migrations.AddField(
            model_name='subscription',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trainer',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.trainer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_type',
            field=models.CharField(blank=True, choices=[(
                'adult', 'Adult'), ('child', 'Child')], max_length=50),  # Изменено с 10 на 50
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(max_length=50),  # Изменено с 20 на 50
        ),
    ]
