# Generated by Django 4.2.3 on 2024-10-12 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_reservation_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='training',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reserve_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='priority_participants',
            field=models.ManyToManyField(blank=True, related_name='priority_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='reserve_participants',
            field=models.ManyToManyField(blank=True, related_name='reserve_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
